FROM node:22.14-alpine AS builder

WORKDIR /app
COPY package.json ./
RUN #npm install
COPY . .
RUN npm run build

FROM node:22.14-alpine

WORKDIR /app
COPY package.json ./
RUN #npm install --only=production
COPY node_modules ./dist
COPY --from=builder /app/dist ./dist
EXPOSE 3001
CMD ["node", "dist/server.js"]
